
clone_depth: 5

image:
  - Visual Studio 2019
  - Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - RelWithDebInfo

clone_folder: c:\project

init:
  - msbuild /version
  - cmake --version

install:
  #- choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
  #- refreshenv
  #- cmake --version

before_build:
  - git submodule update --init --recursive
  - mkdir build && cd build
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" cmake -G"Visual Studio 15 2017" -A "%PLATFORM%" ..
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" cmake -G"Visual Studio 16 2019" -A "%PLATFORM%" ..

build:
  project: c:\project\build\cage.sln

test_script:
  - c:\project\build\result\%CONFIGURATION%\cage-test-core.exe
  - c:\project\build\result\%CONFIGURATION%\cage-asset-database.exe

